workflows:
  default-workflow:
    name: Yemen Finance Build
    max_build_duration: 10
    instance_type: mac_mini_m2
    # هنا تم تفعيل الكاش الذكي لحفظ الحزم واختصار وقت التحميل والتثبيت
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Setup Flutter Project Structure
        script: |
          echo "جاري تهيئة هيكل المشروع اليمني تلقائياً..."
          mkdir -p lib android
          mv main.dart lib/main.dart
      - name: Flutter Packages Get
        script: |
          flutter packages get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
