workflows:
  default-workflow:
    name: Yemen Finance Build
    max_build_duration: 10
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Setup Flutter Project Structure
        script: |
          echo "جاري تهيئة الهيكل الحديث المتوافق لنظام الأرقم المالي..."
          mkdir -p lib
          mv main.dart lib/main.dart || true
          # هنا نجبر الفلاتر على إنشاء مجلد أندرويد حديث يدعم v2 embedding تلقائياً
          flutter create . --platforms=android --force
      - name: Flutter Packages Get
        script: |
          flutter packages get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
