workflows:
  android-release-apk:
    name: Muhasibi Universal Android Release APK

    max_build_duration: 30

    instance_type: mac_mini_m2

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    environment:
      flutter: stable

    triggering:
      events:
        - push

      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Show Flutter version
        script: |
          flutter --version
          dart --version

      - name: Create Android platform if missing
        script: |
          if [ ! -d "android" ]; then
            echo "Android platform folder is missing. Creating it now..."
            flutter create . --platforms=android
          else
            echo "Android platform folder already exists."
          fi

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Analyze Flutter project
        script: |
          flutter analyze || true

      - name: Build Android release APK
        script: |
          flutter clean
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
